output_file = "result.json"
do_rollno_transformation = false
rollno_json = "../../rollno.json"
rollno_regex = "2K21/EE/\\d+"
input_files = [
  "../../../../results/O22_BTECH_III_1516/O22_BTECH_III_1516.decluttered.json",
  "../../../../results/O22_BTECH_ME_III_1519/O22_BTECH_ME_III_1519.json",
]

[subjects]
"MA261" = "MA261"
"EE201" = "EE201"
"EE203" = "EE203"
"EE205" = "EE205"
"EE207" = "EE207"
"FEC" = "FEC"
