output_file = "result.json"
do_rollno_transformation = false
rollno_json = "../../rollno.json"
rollno_regex = "2K21/EC/\\d+"
input_files = [
  "../../../../results/O22_BTECH_III_1516/O22_BTECH_III_1516.decluttered.json",
  "../../../../results/O22_BTECH_ME_III_1519/O22_BTECH_ME_III_1519.json",
]

[subjects]
"EC251" = "EC251"
"EC201" = "EC201"
"EC203" = "EC203"
"EC205" = "EC205"
"EC207" = "EC207"
"FEC" = "FEC"
