output_file = "result.json"
do_rollno_transformation = false
rollno_json = "../../rollno.json"
rollno_regex = "2K21/EN/\\d+"
input_files = [
  "../../../../results/O22_BTECH_III_1516/O22_BTECH_III_1516.decluttered.json",
  "../../../../results/O22_BTECH_ME_III_1519/O22_BTECH_ME_III_1519.json",
]

[subjects]
"CE251" = "CE251"
"EN201" = "EN201"
"EN203" = "EN203"
"EN205" = "EN205"
"EN207" = "EN207"
"FEC" = "FEC"
