output_file = "result.json"
do_rollno_transformation = true
rollno_json = "../../rollno.json"
rollno_regex = "2K21/IT/\\d+"
input_files = [
  "../../../../results/E22_BTECH_II_AUG_1481/E22_BTECH_II_AUG_1481.json",
  "../../../../results/E22_REV_BTECH_R1_1486/E22_REV_BTECH_R1_1486.json",
  "../../../../results/E22_REV_BTECH_MS199_1493/E22_REV_BTECH_MS199_1493.json",
  "../../../../results/E22_REV_BTECH_II_ms199_1498/E22_REV_BTECH_II_ms199_1498.json",
  "../../../../results/E22_REV_BTECH_II_1496/E22_REV_BTECH_II_1496.json",
  "../../../../results/E22_21_REV_BTECH_R1_1501/E22_21_REV_BTECH_R1_1501.json",

]

[subjects]
"MA102" = "MA102"
"AP102" = "AP102"
"AC102 / EE102" = "(?:AC102)|(?:EE102)"
"ME104 / CO102" = "(?:ME104)|(?:CO102)"
"ME106 / ME102" = "(?:ME106)|(?:ME102)"
"FEC" = "FEC"

