output_file = "result.json"
do_rollno_transformation = false
rollno_json = "../../rollno.json"
rollno_regex = "2K21/IT/\\d+"
input_files = [
  "../../../../results/O22_BTECH_III_1516/O22_BTECH_III_1516.decluttered.json",
  "../../../../results/O22_BTECH_ME_III_1519/O22_BTECH_ME_III_1519.json",
]

[subjects]
"EC261" = "EC261"
"IT201" = "IT201"
"IT203" = "IT203"
"IT205" = "IT205"
"IT207" = "IT207"
"FEC" = "FEC"
