output_file = "result.json"
do_rollno_transformation = false
rollno_json = "../../rollno.json"
rollno_regex = "2K21/ME/\\d+"
input_files = [
  "../../../../results/O22_BTECH_III_1516/O22_BTECH_III_1516.decluttered.json",
  "../../../../results/O22_BTECH_ME_III_1519/O22_BTECH_ME_III_1519.json",
]

[subjects]
"PE251" = "PE251"
"ME201" = "ME201"
"ME203" = "ME203"
"ME205" = "ME205"
"ME207" = "ME207"
"FEC" = "FEC"
